"""empty message

Revision ID: 842599a32c6e
Revises: f1f24d975d46
Create Date: 2024-08-05 12:36:37.553581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842599a32c6e'
down_revision = 'f1f24d975d46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_table', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=4000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_table', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=4000),
               nullable=False)

    # ### end Alembic commands ###
