"""empty message

Revision ID: d0f3429c39c1
Revises: 
Create Date: 2024-08-05 09:49:01.640523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f3429c39c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("create sequence user_id_seq start with 5 increment by 1 nocache nocycle")
    op.execute("create sequence chat_id_seq start with 1 increment by 1 nocache nocycle")
    op.execute("create sequence message_id_seq start with 1 increment by 1 nocache nocycle")
    op.create_table('user_table',
    sa.Column('user_id', sa.Integer(), server_default=sa.text('user_id_seq.nextval'), nullable=False),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('chat_table',
    sa.Column('chat_id', sa.Integer(), server_default=sa.text('chat_id_seq.nextval'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_vector', sa.PickleType(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('message_table',
    sa.Column('message_id', sa.Integer(), server_default=sa.text('message_id_seq.nextval'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('is_bot_message', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat_table.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_table')
    op.drop_table('chat_table')
    op.drop_table('user_table')
    op.execute(sa.schema.DropSequence(sa.Sequence("message_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("chat_id_seq")))
    op.execute(sa.schema.DropSequence(sa.Sequence("user_id_seq")))
 
    # ### end Alembic commands ###
